[package]
name = "mgattozzi"
version = "0.1.0"
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]

[dependencies]
iron = "*"
staticfile = "*"
mount = "*"
spongedown = "0.1.1"
clap = "*"
rust-crypto = "^0.2"
