[package]
name = "mgattozzi"
version = "0.1.0"
authors = ["Michael Gattozzi <mgattozzi@gmail.com>"]

[dependencies]
iron = "*"
staticfile = "*"
mount = "*"
spongedown = "0.1.1"
clap = "*"
toml = "0.2"
rayon = "0.5.0"
seahash = "*"
